# Generated by Django 4.2.1 on 2023-06-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='dni',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='owner',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
